# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               文胜的博客
tagline:             乱七八糟的东西，主要是编程
url:                 http://c.wensheng.org/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Wensheng Wang
  url:               http://wensheng.org/
  email:             wenshengwang@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/wensheng/wensheng.github.io

pages_list:
  关于: '/about'
  归档: '/archive'
  Feed: '/atom.xml'
